config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :games, only: [:index,:create, :show, :destroy] do
    resources :participations, only: [:create]
    resources :submissions, only: [:create, :update]
    member do
      patch :finish
    end
    post '/cursor_place', to: 'submissions#cursor_place', as: :cursor_place
  end
  resources :participations, only: [:destroy, :update] do
    collection do
      patch :order
    end
  end
  resources :users, only: [:index, :update] do
    member do
      patch :big_boys
      post :impersonate
    end
    collection do
      post :stop_impersonating
    end
  end
  get '/search', to: 'games#search', as: :search
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :participations, dependent: :destroy
  has_many :games, through: :participations
  has_many :submissions
  has_many :games_won, source: :games, foreign_key: :winner_id
  validates :name, presence: true

  def average_score
    finished_games = participations.where.not(final_score: nil)
    if finished_games.any?
      (finished_games.pluck(:final_score).sum / finished_games.count).round(2)
    else
      'n/a'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update, :big_boys]

  def update
    @game = Game.find(params[:game_id])
    authorize @user
    if @user.update(user_params)
      @participations = @game.participations.order(place: :asc)
      GameChannel.broadcast_to(
        @game,
        modal_close: render_to_string(partial: "users/show_modal", locals: { participation: @game.user_participation(@user) }),
        modal_name: "user-modal-#{@user.id}-#{@user.id}"
      )
      head :ok
    else
      flash[:alert] = @user.errors.full_messages.first
      redirect_to game_path(@game)
    end
  end

  def big_boys
    @game = Game.find(params[:game_id])
    authorize @user
    if @user.update(user_params)
      @big_boys = (User.where.not(big_boys: 0) + @game.users).uniq.sort_by(&:big_boys).reverse
      GameChannel.broadcast_to(
        @game,
        big_boys: render_to_string(partial: "games/big_boys")
      )
      head :ok
    else
      flash[:alert] = @user.errors.full_messages.first
      redirect_to game_path(@game)
    end
  end

  def index
    @users = policy_scope(User).order(:id)
  end

  def impersonate
    authorize current_user
    user = User.find(params[:id])
    impersonate_user(user)
    redirect_to root_path
  end

  def stop_impersonating
    authorize current_user
    stop_impersonating_user
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:big_boys, :name, :email, :time_zone)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_remove_player_modal.html.erb
<div class="modal fade" id="removeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Remove a Player</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table id="leaderboard" class="table table-hover table-sm">
          <thead class="thead-dark">
            <tr>
              <th class="text-left">Players</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% if @participations.any? %>
              <% @participations.each do |participation| %>
                <tr>
                  <td class="text-left"><%= participation.user.name %></td>
                  <td><%= link_to participation_path(participation), method: :delete, data: { confirm: "Leave game and lose progress?" }, class: '' do %><small><i class="fas fa-times"></i></small><% end %></td>
                </tr>
              <% end %>
            <% else %>
              <tr>
                <td>No players yet.</td>
                <td></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/users/_show_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="userModal-<%= participation.user.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= participation.user.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table table-hover table-sm">
          <thead class="thead-dark">
            <tr>
              <th class="text-center">Games</th>
              <th class="text-center">Highest</th>
              <th class="text-center">Lowest</th>
              <th class="text-center">Avg</th>
            </tr>
          </thead>
          <tbody>
            <% if participation.user.participations.where.not(final_score: nil).any? %>
              <tr>
                <td class="text-center"><%= participation.user.participations.where.not(final_score: nil).count %></td>
                <td class="text-center"><%= participation.user.participations.where.not(final_score: nil).order(final_score: :desc).first.final_score %></td>
                <td class="text-center"><%= participation.user.participations.where.not(final_score: nil).order(final_score: :desc).last.final_score %></td>
                <td class="text-center"><%= participation.user.average_score %></td>
              </tr>
            <% else %>
              <tr>
                <td>No other games yet.</td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% if current_user == participation.user %>
          <%= simple_form_for participation.user, remote: true do |f| %>
            <%= f.input :name %>
            <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.all.sort, {}, { class: 'form-control', value: participation.user.time_zone } %>
            <%= hidden_field_tag :game_id, @game.id %>
            <%= f.submit class: 'btn btn-primary mt-3' %>
          <% end %>
        <% end %>
      </div>
      <% unless current_user == participation.user %>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <% if current_user.admin %>
        <% @users.each do |user|  %>
          <div style="margin: 10px; padding: 10px; background-color: white">
            <p><strong>Name:</strong> <%= user.name %></p>
            <p>Sign in as <strong><%= link_to user.email, impersonate_user_path(user), method: :post, style: "text-decoration: none;" %></strong></p>
            <p>Number of game: <%= user.games.count %></p>
            <ul>
              <% user.games.each do |game| %>
                <li>Game: <%= link_to game.id, game_path(game) %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <% else %>
        <div style="margin: 10px; padding: 10px; background-color: white">
          <% if current_user != true_user %>
            You (<%= true_user.email %>) are signed in as <%= current_user.email %>
            <br>
            <%= link_to "Back to admin", stop_impersonating_users_path, method: :post %>
          <% else %>
            <p>You are not authorized for this page.</p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>