config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :games, only: [:index,:create, :show, :destroy] do
    resources :participations, only: [:create]
    resources :submissions, only: [:create, :update]
    member do
      patch :finish
    end
    post '/cursor_place', to: 'submissions#cursor_place', as: :cursor_place
  end
  resources :participations, only: [:destroy, :update] do
    collection do
      patch :order
    end
  end
  resources :users, only: [:index, :update] do
    member do
      patch :big_boys
      post :impersonate
    end
    collection do
      post :stop_impersonating
    end
  end
  get '/search', to: 'games#search', as: :search
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/dmbf29"><i class="fab fa-github"></i></a>
    <a href="mailto:douglasmberkley@gmail.com"><i class="fas fa-envelope"></i></a>
  </div>
  <div class="footer-copyright">
    For when you can't do it in person. Friends, drinks, video chat, and the honor system.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag 'logo.jpg' %>
  <% end %>

<!--   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 -->
  <% if user_signed_in? %>
    <div class="nav-item dropdown navbar-toggler" style="border: none;">
      <%= image_tag "dice.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= simple_form_for Game.new do |f| %>
          <%= f.input :name, as: :hidden %>
          <%#= f.submit "Start a Game", class: 'btn btn-primary' %>
          <%= button_tag type: 'submit', style: 'border:none;background-color:transparent', class: "dropdown-item" do %>
            New Game
          <% end %>
        <% end %>
        <%#= link_to "New Game", root_path, class: "dropdown-item" %>
        <%= link_to "All Games", games_path, class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </div>
  <% else %>
    <div class="navbar-toggler" style="border: none;">
      <%= link_to "Login", new_user_session_path, class: "nav-link btn btn-warning", style: 'color: white;' %>
    </div>
  <% end %>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Games", games_path, class: "nav-link navbar-lewagon-link" %>
        </li>
      <% end %>
      <li>
        <%= simple_form_for :search, url: search_path, method: :get do |f| %>
          <div class="search-form-control form-group">
            <input class="form-control string required" type="text" name="id" id="search_query" placeholder="Game #" />
            <button name="button" type="submit" class="btn btn-flat">
              <i class="fas fa-search"></i>
            </button>
          </div>
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item mr-3">
          <%#= link_to "New Game", "#", class: "btn btn-info" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "dice.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= simple_form_for Game.new do |f| %>
              <%= f.input :name, as: :hidden %>
              <%#= f.submit "Start a Game", class: 'btn btn-primary' %>
              <%= button_tag type: 'submit', style: 'border:none;background-color:transparent', class: "dropdown-item" do %>
                New Game
              <% end %>
            <% end %>
            <%#= link_to "New Game", root_path, class: "dropdown-item" %>
            <%= link_to "All Games", games_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link btn btn-link ml-3", style: 'color: white;' %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link btn btn-warning ml-3", style: 'color: white;' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>