config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :games, only: [:index,:create, :show, :destroy] do
    resources :participations, only: [:create]
    resources :submissions, only: [:create, :update]
    member do
      patch :finish
    end
    post '/cursor_place', to: 'submissions#cursor_place', as: :cursor_place
  end
  resources :participations, only: [:destroy, :update] do
    collection do
      patch :order
    end
  end
  resources :users, only: [:index, :update] do
    member do
      patch :big_boys
      post :impersonate
    end
    collection do
      post :stop_impersonating
    end
  end
  get '/search', to: 'games#search', as: :search
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :submissions, dependent: :destroy
  has_many :participations, dependent: :destroy
  has_many :users, through: :participations
  belongs_to :winner, class_name: "User", optional: true
  before_validation :add_hex_code
  validates_uniqueness_of :code
  before_destroy :destroy_submissions

  def to_param
    code
  end

  def destroy_submissions
    submissions.with_deleted.each(&:destroy_fully!)
  end

  def add_hex_code
    self.code = SecureRandom.alphanumeric(6).upcase if code.nil?
  end

  def add_creator(user)
    participation = user_participation(user)
    if participation
      participation.creator = true
      participation.save
    else
      Participation.create(game: self, user: user, creator: true)
    end
  end

  def user_participation(user)
    participations.find_by(user: user)
  end

  def finish!
    participations.each do |participation|
      next unless participation.submissions.count == 15

      score = participation.user.submissions.where(game: self).pluck(:value).sum
      participation.final_score = score
      participation.save
    end
    self.winner = participations.order(final_score: :desc).first.user if participations.count > 1
    save
  end

  def nonbonus_submissions
    submissions.where.not(category: [Category.yahtzee_bonus, Category.top_bonus])
  end

  def full?
    participations.count >=5
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :search, :finish, :destroy]
  before_action :set_leaderboard, only: [:show]
  skip_after_action :verify_authorized, only: [:search]
  before_action :set_table_values, only: [:show]

  def create
    @game = Game.new(game_params)
    authorize @game
    if @game.save
      if params[:game][:restart] == 'true'
        old_game = Game.find(params[:game][:previous_id])
        old_game.finish!
        GameChannel.broadcast_to(
          old_game,
          new_game: render_to_string(partial: "games/invite", locals: { user: current_user, game: @game, participation: Participation.new })
        )
      end
      @game.add_creator(current_user)
      redirect_to game_path(@game)
    else
      render 'pages/home'
    end
  end

  def show
    authorize @game
    @participations = @game.participations.includes(:user).order(place: :asc)
    @categories = Category.order(place: :asc)
    @top_categories = @categories.where(top_half: true)
    @bottom_categories = @categories.where(top_half: false)
    @participation = @game.user_participation(current_user) || Participation.new
    @big_boys = (User.where.not(big_boys: 0) + @game.users).uniq.sort_by(&:big_boys).reverse
  end

  def search
    if @game
      redirect_to game_path(@game)
    else
      flash[:alert] = "Could not find game with that code."
      redirect_to root_path
    end
  end

  def index
    @games = policy_scope(Game).order(created_at: :desc)
  end

  def finish
    @game.finish!
    authorize @game
    redirect_to game_path(@game)
  end

  def destroy
    @game.destroy
    authorize @game
    redirect_to games_path
  end

  private

  def game_params
    params.require(:game).permit(:code, :name)
  end

  def set_game
    @game = Game.find_by(code: params[:id])
  end

  def set_leaderboard
    @leaderboard = Participation.includes(:user).where.not(final_score: nil).order(final_score: :desc).first(10)
    @others = Participation.includes(:user)
    .where.not(final_score: nil)
    .where.not(id: @leaderboard)
    .where.not(user_id: @leaderboard.pluck(:user_id))
    .order(final_score: :desc).uniq(&:user_id)
    @all_participations = Participation.where.not(final_score: nil).order(final_score: :desc)
    @leaderboard += @others
  end

  def set_table_values
    @participations = @game.participations.order(place: :asc)
    @categories = Category.order(place: :asc)
    @top_categories = @categories.where(top_half: true)
    @bottom_categories = @categories.where(top_half: false)
    @participation = @game.user_participation(current_user) || Participation.new
  end
end

app/views/games/_action_btns.html.erb
<%= simple_form_for Game.new, html: { class: "#{'d-flex my-2' if @game.winner}" } do |f| %>
  <%= hidden_field_tag 'game[restart]', true %>
  <%= hidden_field_tag 'game[previous_id]', @game.id %>
  <%= f.input :name, as: :hidden %>
  <%= f.submit "Play Again", class: "btn btn-primary #{'d-none' unless @game.winner }", id: 'play-again-btn', data: { confirm: "Start new game and invite others?" } %>
<% end %>
<%#= simple_form_for @game, method: :patch, url: finish_game_path(@game), remote: true do |f| %>
  <%#= f.submit "Submit Scores", class: "btn btn-light" %>
<%# end %>

<!-- Hidden/Triggered by JS -->
<button type="button" class="btn btn-primary d-none" data-toggle="modal" data-target="#exampleModal" id="game-invite-btn">
  Invitation
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Play again?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="new-game-invitation">

      </div>
    </div>
  </div>
</div>

app/views/games/_big_boys.html.erb
<table id="leaderboard" class="table table-hover table-sm side-table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Big Boys</th>
      <th class="tex-center">#</th>
    </tr>
  </thead>
  <tbody>
    <% if @big_boys.any? %>
      <% @big_boys.each do |user| %>
        <tr>
          <td class="d-flex">
            <%= user.name %>
            <%= simple_form_for user, remote: true, method: :patch, url: big_boys_user_path(user), remote: true, html: { style: 'display: flex;justify-content: center', id: "edit_user_pos_#{user.id}" } do |f| %>
              <%= f.input :big_boys, as: :hidden, input_html: { value: user.big_boys + 1, id: "user_big_boys_#{user.id}" } %>
              <%= hidden_field_tag :game_id, @game.id, id: "game_id_#{user.id}" %>
              <%= button_tag type: 'submit', data: { confirm: "+1 to #{user.name}'s' big boys?" }, class: 'gray', style: 'border: none;background-color: transparent;display: flex;align-items:center;vertical-align:center' do %>
                <small class="lighter-gray"><i class="far fa-plus-square"></i></small>
              <% end %>
            <% end %>
            <%= simple_form_for user, remote: true, method: :patch, url: big_boys_user_path(user), remote: true, html: { style: 'display: flex;justify-content: center', id: "edit_user_neg_#{user.id}" } do |f| %>
              <%= f.input :big_boys, as: :hidden, input_html: { value: user.big_boys - 1, id: "user_big_boys_neg_#{user.id}" } %>
              <%= hidden_field_tag :game_id, @game.id, id: "game_id_neg_#{user.id}" %>
              <%= button_tag type: 'submit', data: { confirm: "-1 to #{user.name}'s' big boys?" }, class: 'gray', style: 'border: none;background-color: transparent;display: flex;align-items:center;padding-left:0;vertical-align:center' do %>
                <small class="lighter-gray"><i class="far fa-minus-square"></i></small>
              <% end %>
            <% end %>
          </td>
          <td class="tex-center"><%= user.big_boys %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td>No big boys yet.</td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/_dice.html.erb
<form name="user" method="post" action="#" onSubmit="return ValidateForm(this,'box')">


<div style="position: absolute; top: 1px; left: 85px;">
<div id="bouncy1">
<img name="one" src="dice/dice1-1.jpg" > </div>

<div style="position: absolute; top: 0px; left: 135px;">
<div id="bouncy2">
<img name="two" src="dice/dice2-1.jpg" > </div>

<div style="position: absolute; top: 0px; left: 135px;">
<div id="bouncy3">
<img name="three" src="dice/dice3-1.jpg" > </div>

<div style="position: absolute; top: 0px; left: 135px;">
<div id="bouncy4">
<img name="four" src="dice/dice4-1.jpg" > </div>

<div style="position: absolute; top: 0px; left: 135px;">
<div id="bouncy5">
<img name="five" src="dice/dice5-1.jpg" > </div>







<div style="position: absolute; top: 115px; left: -475px;">
<input type="checkbox" name="box" value="one" id ="one" >
</div>

<div style="position: absolute; top: 135px; left: -485px;">
<label for = "one">HOLD</label>
</div>

<div style="position: absolute; top: 115px; left: -340px;">
<input type="checkbox" name="box" value="two" id ="two" >
</div>

<div style="position: absolute; top: 135px; left: -350px;">
<label for = "two">HOLD</label>
</div>

<div style="position: absolute; top: 115px; left: -205px;">
<input type="checkbox" name="box" value="three" id ="three" >
</div>

<div style="position: absolute; top: 135px; left: -215px;">
<label for = "three">HOLD</label>
</div>

<div style="position: absolute; top: 115px; left: -70px;">
<input type="checkbox" name="box" value="four" id ="four" >
</div>

<div style="position: absolute; top: 135px; left: -80px;">
<label for = "four">HOLD</label>
</div>

<div style="position: absolute; top: 115px; left: 65px;">
<input type="checkbox" name="box" value="five" id ="five" >
</div>

<div style="position: absolute; top: 135px; left: 55px;">
<label for = "five">HOLD</label>
</div>







<div style="position: absolute; top: 200px; left: -226px;">
     <a href="javascript:SetChecked(0,'box')">
<font face="Arial, Helvetica, sans-serif" size="3">Clear
                  All</font>
</a>
</div>



<div style="position: absolute; top: 245px; left: -295px;">
<p align="center">
<a href="javascript:georgeroll()">
<img src="dice/rollbutton.jpg" width="200" height="60" name="roll" border=0>
</a>
</p>

</div>

 <script>
   <script language="javascript">
<!--


//load button images

var pic=new Array();
<!-- pic[0]=new Image(); -->
<!-- pic[0].src="dice/rollbutton.jpg"; -->



//change button function

function chButton(name,source){

var picture=eval('document' + '.' + name);
picture.src=source;

}


//-->
</script>
<script language="javascript">
<!--




//set up variables




var ck=new Array();
var count=0;
var score = new Array();
var pos = new Array();
var x = 0;

var fld= new Array('ones','twos','threes','fours','fives','sixes');
var dice= new Array(94);

//load dice images

dice[0]= new Image();
dice[0].src="dice/dice1-1.jpg";
dice[1]= new Image();
dice[1].src="dice/dice1-2.jpg";
dice[2]= new Image();
dice[2].src="dice/dice1-3.jpg";
dice[3]= new Image();
dice[3].src="dice/dice1-4.jpg";
dice[4]= new Image();
dice[4].src="dice/dice1-5.jpg";
dice[5]= new Image();
dice[5].src="dice/dice1-6.jpg";
dice[6]= new Image();
dice[6].src="dice/dice1-7.jpg";
dice[7]= new Image();
dice[7].src="dice/dice1-8.jpg";
dice[8]= new Image();
dice[8].src="dice/dice1-9.jpg";
dice[9]= new Image();
dice[9].src="dice/dice1-10.jpg";
dice[10]= new Image();
dice[10].src="dice/dice1-11.jpg";
dice[11]= new Image();
dice[11].src="dice/dice1-12.jpg";
dice[12]= new Image();
dice[12].src="dice/dice1-13.jpg";
dice[13]= new Image();
dice[13].src="dice/dice1-14.jpg";
dice[14]= new Image();
dice[14].src="dice/dice1-15.jpg";
dice[15]= new Image();
dice[15].src="dice/dice1-16.jpg";
dice[16]= new Image();
dice[16].src="dice/dice1-17.jpg";

dice[17]= new Image();
dice[17].src="dice/dice2-1.jpg";
dice[18]= new Image();
dice[18].src="dice/dice2-2.jpg";
dice[19]= new Image();
dice[19].src="dice/dice2-3.jpg";
dice[20]= new Image();
dice[20].src="dice/dice2-4.jpg";
dice[21]= new Image();
dice[21].src="dice/dice2-5.jpg";
dice[22]= new Image();
dice[22].src="dice/dice2-6.jpg";
dice[23]= new Image();
dice[23].src="dice/dice2-7.jpg";
dice[24]= new Image();
dice[24].src="dice/dice2-8.jpg";
dice[25]= new Image();
dice[25].src="dice/dice2-9.jpg";
dice[26]= new Image();
dice[26].src="dice/dice2-10.jpg";
dice[27]= new Image();
dice[27].src="dice/dice2-11.jpg";
dice[28]= new Image();
dice[28].src="dice/dice2-12.jpg";
dice[29]= new Image();
dice[29].src="dice/dice2-13.jpg";
dice[30]= new Image();
dice[30].src="dice/dice2-14.jpg";
dice[31]= new Image();
dice[31].src="dice/dice2-15.jpg";

dice[32]= new Image();
dice[32].src="dice/dice3-1.jpg";
dice[33]= new Image();
dice[33].src="dice/dice3-2.jpg";
dice[34]= new Image();
dice[34].src="dice/dice3-3.jpg";
dice[35]= new Image();
dice[35].src="dice/dice3-4.jpg";
dice[36]= new Image();
dice[36].src="dice/dice3-5.jpg";
dice[37]= new Image();
dice[37].src="dice/dice3-6.jpg";
dice[38]= new Image();
dice[38].src="dice/dice3-7.jpg";
dice[39]= new Image();
dice[39].src="dice/dice3-8.jpg";
dice[40]= new Image();
dice[40].src="dice/dice3-9.jpg";
dice[41]= new Image();
dice[41].src="dice/dice3-10.jpg";
dice[42]= new Image();
dice[42].src="dice/dice3-11.jpg";
dice[43]= new Image();
dice[43].src="dice/dice3-12.jpg";
dice[44]= new Image();
dice[44].src="dice/dice3-13.jpg";
dice[45]= new Image();
dice[45].src="dice/dice3-14.jpg";

dice[46]= new Image();
dice[46].src="dice/dice4-1.jpg";
dice[47]= new Image();
dice[47].src="dice/dice4-2.jpg";
dice[48]= new Image();
dice[48].src="dice/dice4-3.jpg";
dice[49]= new Image();
dice[49].src="dice/dice4-4.jpg";
dice[50]= new Image();
dice[50].src="dice/dice4-5.jpg";
dice[51]= new Image();
dice[51].src="dice/dice4-6.jpg";
dice[52]= new Image();
dice[52].src="dice/dice4-7.jpg";
dice[53]= new Image();
dice[53].src="dice/dice4-8.jpg";
dice[54]= new Image();
dice[54].src="dice/dice4-9.jpg";
dice[55]= new Image();
dice[55].src="dice/dice4-10.jpg";
dice[56]= new Image();
dice[56].src="dice/dice4-11.jpg";
dice[57]= new Image();
dice[57].src="dice/dice4-12.jpg";
dice[58]= new Image();
dice[58].src="dice/dice4-13.jpg";
dice[59]= new Image();
dice[59].src="dice/dice4-14.jpg";
dice[60]= new Image();
dice[60].src="dice/dice4-15.jpg";
dice[61]= new Image();
dice[61].src="dice/dice4-16.jpg";

dice[62]= new Image();
dice[62].src="dice/dice5-1.jpg";
dice[63]= new Image();
dice[63].src="dice/dice5-2.jpg";
dice[64]= new Image();
dice[64].src="dice/dice5-3.jpg";
dice[65]= new Image();
dice[65].src="dice/dice5-4.jpg";
dice[66]= new Image();
dice[66].src="dice/dice5-5.jpg";
dice[67]= new Image();
dice[67].src="dice/dice5-6.jpg";
dice[68]= new Image();
dice[68].src="dice/dice5-7.jpg";
dice[69]= new Image();
dice[69].src="dice/dice5-8.jpg";
dice[70]= new Image();
dice[70].src="dice/dice5-9.jpg";
dice[71]= new Image();
dice[71].src="dice/dice5-10.jpg";
dice[72]= new Image();
dice[72].src="dice/dice5-11.jpg";
dice[73]= new Image();
dice[73].src="dice/dice5-12.jpg";
dice[74]= new Image();
dice[74].src="dice/dice5-13.jpg";
dice[75]= new Image();
dice[75].src="dice/dice5-14.jpg";
dice[76]= new Image();
dice[76].src="dice/dice5-15.jpg";

dice[77]= new Image();
dice[77].src="dice/dice6-1.jpg";
dice[78]= new Image();
dice[78].src="dice/dice6-2.jpg";
dice[79]= new Image();
dice[79].src="dice/dice6-3.jpg";
dice[80]= new Image();
dice[80].src="dice/dice6-4.jpg";
dice[81]= new Image();
dice[81].src="dice/dice6-5.jpg";
dice[82]= new Image();
dice[82].src="dice/dice6-6.jpg";
dice[83]= new Image();
dice[83].src="dice/dice6-7.jpg";
dice[84]= new Image();
dice[84].src="dice/dice6-8.jpg";
dice[85]= new Image();
dice[85].src="dice/dice6-9.jpg";
dice[86]= new Image();
dice[86].src="dice/dice6-10.jpg";
dice[87]= new Image();
dice[87].src="dice/dice6-11.jpg";
dice[88]= new Image();
dice[88].src="dice/dice6-12.jpg";
dice[89]= new Image();
dice[89].src="dice/dice6-13.jpg";
dice[90]= new Image();
dice[90].src="dice/dice6-14.jpg";
dice[91]= new Image();
dice[91].src="dice/dice6-15.jpg";
dice[92]= new Image();
dice[92].src="dice/dice6-16.jpg";
dice[93]= new Image();
dice[93].src="dice/dice6-17.jpg";









//random number generator

function ranNum(){

for(var i = 0; i < dice.length; i++){
var j = Math.floor(Math.random() * dice.length);

return j;
 }
}



function pausecomp(millis)
{
var date = new Date();
var curDate = null;

do { curDate = new Date(); }
while(curDate-date < millis);
}



function roll(){




//determine which roll
x++;

<!--
if(x > 2000){
<!-- chButton('roll','dice/rollbutton.jpg'); -->
<!-- alert("Please Select New Game."); -->
<!-- chButton('roll','dice/rollbutton.jpg'); -->

}
else{
if(x==1){
<!-- chButton('roll','dice/rollbutton.jpg'); -->
}
-->


//check for held dice
var snd = new Audio("dicesound4.mp3");

for(var a = 0;a < document.user.box.length;a++){
  if(document.user.box[a].checked == false){
  pos[a] = document.user.box[a].value;
}
else{
  if(document.user.box[a].checked == true){
  pos[a] = "skip";

}
  }
}

for(var i = 0; i < pos.length; i++){
  var n= eval('document' + '.' + pos[i]);

  if(pos[i] == "skip"){
}

//if not held roll dice
else{


  var d=ranNum();

  score[i] = (d + 1);

pausecomp(0);
n.src=dice[d].src;

snd.play();

<!-- soundManager.play('aDrumSound'); --!



}
  }


}

}





//clear dice for next roll
function clearDice(){


var n=new Array("one","two","three","four","five","six");
for(var i=0;i < n.length;i++){
var p=eval('document' + '.' + n[i]);

p.src="dice/dice.jpg";
delete ck[i];



}

ckFrmState();
}



//clear all values for new game
function newGame(){
ck.length=0;
<!-- chButton('roll','dice/rollbutton.jpg'); -->

x=0;
count=0;
document.user.reset();

}


//-->

function georgeroll(){

           if ($('#one').is (":not(:checked)"))
{
   $("#bouncy1").click();
}

                   if ($('#two').is (":not(:checked)"))
{
   $("#bouncy2").click();
}

                   if ($('#three').is (":not(:checked)"))
{
   $("#bouncy3").click();
}

                   if ($('#four').is (":not(:checked)"))
{
   $("#bouncy4").click();
}


                    if ($('#five').is (":not(:checked)"))
{
   $("#bouncy5").click();
}



          roll();


 }




$(function(){

  //Add bounce effect on Click of the DIV
  $('#bouncy1').click(function () {
      $(this).effect("bounce", { times:2 }, 105);
  });

  $('#bouncy2').click(function () {
      $(this).effect("bounce", { times:3 }, 115);
  });

  $('#bouncy3').click(function () {
      $(this).effect("bounce", { times:2 }, 135);
  });

  $('#bouncy4').click(function () {
      $(this).effect("bounce", { times:3 }, 115);
  });

  $('#bouncy5').click(function () {
      $(this).effect("bounce", { times:2 }, 125);
  });



  //Bounce all DIVs on click of button
  $("#bounceAll").click(function(){


                   if ($('#one').is (":not(:checked)"))
{
   $("#bouncy1").click();
}

                   if ($('#two').is (":not(:checked)"))
{
   $("#bouncy2").click();
}

                   if ($('#three').is (":not(:checked)"))
{
   $("#bouncy3").click();
}

                   if ($('#four').is (":not(:checked)"))
{
   $("#bouncy4").click();
}

                   if ($('#five').is (":not(:checked)"))
{
   $("#bouncy5").click();
}






                    roll();



  });
});

 </script>

app/views/games/_invite.html.erb
<p><%= user.name %> has invited you to play another game.</p>
<%= link_to game_participations_path(game, participation), method: :post, class: 'btn btn-primary' do %>
  <i class="fas fa-play-circle"></i> Join
<% end %>

<button type="button" class="btn btn-secondary" data-dismiss="modal">No Thanks</button>

app/views/games/_leaderboard.html.erb
<table id="leaderboard" class="table table-hover table-sm side-table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Leaderboard</th>
      <th class="text-center">Avg</th>
      <th class="text-center">High</th>
    </tr>
  </thead>
  <tbody>
    <% if @leaderboard.any? %>
      <% @users_displayed = [] %>
      <% @leaderboard.each_with_index do |leader, index| %>
        <% if index == 10 %>
          <tr class="wrapper-subtle-gray"><td></td><td></td><td></td></tr>
        <% end %>
        <tr class="<%#= 'participation-border-header' if @game.users.include?(leader.user) %>">
          <td><%= display_index(index, leader) %><%= leader.user.name %></td>
          <td class="text-center"><%= display_average_score(leader.user) %></td>
          <td style="text-align: center;"><%= leader.final_score %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td>No scores yet.</td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/_top_row.html.erb
<div style="display:flex;align-items:center;flex:50%;flex-grow:0;padding-right: 15px;">
  <% if @participation.id && @game.winner %>
    <%= render 'games/action_btns' %>
  <% elsif @participation.id  %>
    <%= render 'games/action_btns' %>
    <div class="d-flex w-100" id='share-group'>
      <button style='font-size: 13px;' class="btn btn-secondary my-2 d-flex align-items-center" id="share-btn" data-container="body" data-toggle="popover" data-placement="top" data-content="Copied to clipboard.">
        Share&nbsp;<i class="fas fa-share-alt"></i>
      </button>
      <p class="my-2 w-100">
        <input id="share-link" type="text" value="<%= ENV['DOMAIN'] + url_for(@game) %>" readonly class='form-control w-100'>
      </p>
    </div>
  <% else %>
    <div class="my-2">
      <%= link_to game_participations_path(@game, @participation), method: :post, remote: true, class: 'btn btn-primary', style: "font-size: 13px;" do %>
        <i class="fas fa-play-circle"></i> Join
      <% end %>
    </div>
  <% end %>
</div>
<div>
  <button id="wide-view-btn"v class="btn btn-light m-0" style='font-size: 13px;'>Wide View</button>
  <% if @participation.id %>
    <p id="dice-btn" class="btn btn-primary m-0" style='font-size: 13px;'>
      Dice <i class="fas fa-chevron-down"></i>
    </p>
  <% end %>
</div>

app/views/games/index.html.erb
<div class="container my-5">
  <h1>Games</h1>
  <% if @games.any? %>
    <% @games.each do |game| %>
      <div class="notification">
        <!-- <img src='https://kitt.lewagon.com/placeholder/users/arthur-littm' class="avatar-large" /> -->
        <div class="notification-content">
          <p><small><%= game.created_at.strftime('%A, %b %d') %></small></p>
          <% game.participations.each do |participation| %>
            <% if participation.final_score %>
              <p><%= participation.user.name %> - <%= participation.final_score %> <% if game.winner == participation.user %><i class="fas fa-star yellow"></i><% end %></p>
            <% else %>
              <p><%= participation.user.name %></p>
            <% end %>
          <% end %>
        </div>

        <div class="notification-actions">
          <%= link_to game_path(game) do %>
            View <i class="fas fa-eye"></i>
          <% end %>
          <% if game.users.include?(current_user) %>
            <%= link_to participation_path(game.participations.find_by(user: current_user)), method: :delete, data: { confirm: "Leave game and lose progress?" } do %>
              Leave <i class="far fa-trash-alt"></i>
            <% end %>
          <% end %>
          <% if current_user.admin %>
            <%= link_to game_path(game), method: :delete, data: { confirm: "Delete game and lose all progress?" } do %>
              Delete <i class="far fa-trash-alt"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="notification">
        <div class="notification-content">
          <p>Nothing yet. Get to playing!</p>
        </div>

        <div class="notification-actions">
        </div>
      </div>
  <% end %>
</div>

app/views/games/show.html.erb
<!-- changing this div will break everything -->
<div class="container" id="game" data-game-id="<%= @game.id %>">

  <%= simple_form_for @game, url: game_cursor_place_path(@game), method: :post, remote: true, html: { id: 'cursor_place' } do |f| %>
    <%= hidden_field_tag :cursor_place_id, nil, id: "cursor_place_id" %>
    <%= hidden_field_tag :participation_place, @participation.place %>
    <%= hidden_field_tag :user_id, current_user.id %>
  <% end %>


  <div class="row justify-content-center">
    <div class="col-12 col-lg-10">
      <div class="d-flex justify-content-between align-items-center">
        <%= render 'games/top_row' %>
      </div>
    </div>
  </div>

  <div class="row justify-content-center">
    <iframe src="https://www.elversonpuzzle.com/yahtzee-dice-roller.html#element164" frameborder="0" width="100%" class="mb-3 d-none" height="350px"></iframe>
    <div class="col-12 col-sm-8 col-md-8 col-lg-6" id="left-column">
      <%= render 'games/table' %>
      <div class="d-flex justify-content-center">
      </div>
      <div class="mb-5">
        <%= render 'submissions/list' %>
      </div>
    </div>
    <div class="col-12 col-sm-4 col-md-4" id="right-column">
      <div id="participations-container">
        <%= render 'participations/list' %>
      </div>
      <div id="leaderboard-container">
        <%= render 'games/leaderboard' %>
      </div>
      <div id="big-boys-container">
        <%= render 'games/big_boys' %>
      </div>
      <div class="text-right d-flex flex-column">
        <% if @participations.any? && @participation.id %>
          <%= link_to 'Remove a player', '#', data: { toggle: "modal", target: '#removeModal' }, class: 'mb-1 lighter-gray'  %>
          <div id="remove-modal">
            <%= render 'participations/remove_modal' %>
          </div>
        <% end %>
        <% if @participation.id %>
          <%= link_to 'Leave game', participation_path(@participation), method: :delete, data: { confirm: "Leave game and lose progress?" }, class: 'mb-3 lighter-gray'  %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">

  </div>
</div>